// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AgentConfig 单个 Agent 的配置
 */
export class AgentConfig {
    /**
     * Creates a new AgentConfig instance.
     * @param {Partial<AgentConfig>} [$$source = {}] - The source object to create the AgentConfig.
     */
    constructor($$source = {}) {
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["model"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["variant"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["skills"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["mcps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["temperature"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentConfig}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField2_0($$parsedSource["skills"]);
        }
        if ("mcps" in $$parsedSource) {
            $$parsedSource["mcps"] = $$createField3_0($$parsedSource["mcps"]);
        }
        return new AgentConfig(/** @type {Partial<AgentConfig>} */($$parsedSource));
    }
}

/**
 * AppendPromptDiff 单个 agent 的差异
 */
export class AppendPromptDiff {
    /**
     * Creates a new AppendPromptDiff instance.
     * @param {Partial<AppendPromptDiff>} [$$source = {}] - The source object to create the AppendPromptDiff.
     */
    constructor($$source = {}) {
        if (!("agent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent"] = "";
        }
        if (!("store" in $$source)) {
            /**
             * 持久存储内容
             * @member
             * @type {string}
             */
            this["store"] = "";
        }
        if (!("file" in $$source)) {
            /**
             * .md 文件内容
             * @member
             * @type {string}
             */
            this["file"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendPromptDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppendPromptDiff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppendPromptDiff(/** @type {Partial<AppendPromptDiff>} */($$parsedSource));
    }
}

/**
 * MCPInfo represents a parsed MCP server entry
 */
export class MCPInfo {
    /**
     * Creates a new MCPInfo instance.
     * @param {Partial<MCPInfo>} [$$source = {}] - The source object to create the MCPInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "local" or "remote"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * for local: display command
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * for remote: the URL
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "config" or "plugin"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MCPInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPInfo(/** @type {Partial<MCPInfo>} */($$parsedSource));
    }
}

/**
 * MainAgentConfig represents an agent configuration in the main config
 */
export class MainAgentConfig {
    /**
     * Creates a new MainAgentConfig instance.
     * @param {Partial<MainAgentConfig>} [$$source = {}] - The source object to create the MainAgentConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["disable"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MainAgentConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MainAgentConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MainAgentConfig(/** @type {Partial<MainAgentConfig>} */($$parsedSource));
    }
}

/**
 * MainConfig represents the main opencode.json
 */
export class MainConfig {
    /**
     * Creates a new MainConfig instance.
     * @param {Partial<MainConfig>} [$$source = {}] - The source object to create the MainConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["$schema"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["small_model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["plugin"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: MainAgentConfig } | undefined}
             */
            this["agent"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: MainProviderConfig } | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["mcp"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MainConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MainConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugin" in $$parsedSource) {
            $$parsedSource["plugin"] = $$createField3_0($$parsedSource["plugin"]);
        }
        if ("agent" in $$parsedSource) {
            $$parsedSource["agent"] = $$createField4_0($$parsedSource["agent"]);
        }
        if ("provider" in $$parsedSource) {
            $$parsedSource["provider"] = $$createField5_0($$parsedSource["provider"]);
        }
        if ("mcp" in $$parsedSource) {
            $$parsedSource["mcp"] = $$createField6_0($$parsedSource["mcp"]);
        }
        return new MainConfig(/** @type {Partial<MainConfig>} */($$parsedSource));
    }
}

/**
 * MainProviderConfig represents a provider configuration in the main config
 */
export class MainProviderConfig {
    /**
     * Creates a new MainProviderConfig instance.
     * @param {Partial<MainProviderConfig>} [$$source = {}] - The source object to create the MainProviderConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MainProviderConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MainProviderConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField0_0($$parsedSource["options"]);
        }
        return new MainProviderConfig(/** @type {Partial<MainProviderConfig>} */($$parsedSource));
    }
}

/**
 * Preset 预设配置
 */
export class Preset {
    /**
     * Creates a new Preset instance.
     * @param {Partial<Preset>} [$$source = {}] - The source object to create the Preset.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AgentConfig | null | undefined}
             */
            this["orchestrator"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AgentConfig | null | undefined}
             */
            this["oracle"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AgentConfig | null | undefined}
             */
            this["librarian"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AgentConfig | null | undefined}
             */
            this["explorer"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AgentConfig | null | undefined}
             */
            this["designer"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AgentConfig | null | undefined}
             */
            this["fixer"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Preset}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("orchestrator" in $$parsedSource) {
            $$parsedSource["orchestrator"] = $$createField0_0($$parsedSource["orchestrator"]);
        }
        if ("oracle" in $$parsedSource) {
            $$parsedSource["oracle"] = $$createField1_0($$parsedSource["oracle"]);
        }
        if ("librarian" in $$parsedSource) {
            $$parsedSource["librarian"] = $$createField2_0($$parsedSource["librarian"]);
        }
        if ("explorer" in $$parsedSource) {
            $$parsedSource["explorer"] = $$createField3_0($$parsedSource["explorer"]);
        }
        if ("designer" in $$parsedSource) {
            $$parsedSource["designer"] = $$createField4_0($$parsedSource["designer"]);
        }
        if ("fixer" in $$parsedSource) {
            $$parsedSource["fixer"] = $$createField5_0($$parsedSource["fixer"]);
        }
        return new Preset(/** @type {Partial<Preset>} */($$parsedSource));
    }
}

/**
 * PresetDiff 预设差异
 */
export class PresetDiff {
    /**
     * Creates a new PresetDiff instance.
     * @param {Partial<PresetDiff>} [$$source = {}] - The source object to create the PresetDiff.
     */
    constructor($$source = {}) {
        if (!("store_active" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_active"] = "";
        }
        if (!("file_active" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_active"] = "";
        }
        if (!("differences" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["differences"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresetDiff}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("differences" in $$parsedSource) {
            $$parsedSource["differences"] = $$createField2_0($$parsedSource["differences"]);
        }
        return new PresetDiff(/** @type {Partial<PresetDiff>} */($$parsedSource));
    }
}

/**
 * PresetStoreData 持久存储结构
 */
export class PresetStoreData {
    /**
     * Creates a new PresetStoreData instance.
     * @param {Partial<PresetStoreData>} [$$source = {}] - The source object to create the PresetStoreData.
     */
    constructor($$source = {}) {
        if (!("active_preset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["active_preset"] = "";
        }
        if (!("presets" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: Preset | null }}
             */
            this["presets"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetStoreData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresetStoreData}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField1_0($$parsedSource["presets"]);
        }
        return new PresetStoreData(/** @type {Partial<PresetStoreData>} */($$parsedSource));
    }
}

/**
 * SkillInfo represents a discovered skill
 */
export class SkillInfo {
    /**
     * Creates a new SkillInfo instance.
     * @param {Partial<SkillInfo>} [$$source = {}] - The source object to create the SkillInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "config", "plugin", or "agent"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo(/** @type {Partial<SkillInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = MainAgentConfig.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = MainProviderConfig.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = AgentConfig.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = Preset.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $$createType9);
