// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AgentConfig 单个 Agent 的配置
 */
export class AgentConfig {
    "model": any;
    "variant"?: string;
    "skills"?: string[];
    "mcps"?: string[];
    "temperature"?: number | null;

    /** Creates a new AgentConfig instance. */
    constructor($$source: Partial<AgentConfig> = {}) {
        if (!("model" in $$source)) {
            this["model"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentConfig {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField2_0($$parsedSource["skills"]);
        }
        if ("mcps" in $$parsedSource) {
            $$parsedSource["mcps"] = $$createField3_0($$parsedSource["mcps"]);
        }
        return new AgentConfig($$parsedSource as Partial<AgentConfig>);
    }
}

/**
 * AppendPromptDiff 单个 agent 的差异
 */
export class AppendPromptDiff {
    "agent": string;

    /**
     * 持久存储内容
     */
    "store": string;

    /**
     * .md 文件内容
     */
    "file": string;

    /** Creates a new AppendPromptDiff instance. */
    constructor($$source: Partial<AppendPromptDiff> = {}) {
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }
        if (!("store" in $$source)) {
            this["store"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendPromptDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): AppendPromptDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppendPromptDiff($$parsedSource as Partial<AppendPromptDiff>);
    }
}

/**
 * MCPInfo represents a parsed MCP server entry
 */
export class MCPInfo {
    "name": string;

    /**
     * "local" or "remote"
     */
    "type": string;

    /**
     * for local: display command
     */
    "command": string;

    /**
     * for remote: the URL
     */
    "url": string;

    /**
     * "config" or "plugin"
     */
    "source": string;

    /** Creates a new MCPInfo instance. */
    constructor($$source: Partial<MCPInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPInfo($$parsedSource as Partial<MCPInfo>);
    }
}

/**
 * MainAgentConfig represents an agent configuration in the main config
 */
export class MainAgentConfig {
    "disable"?: boolean;

    /** Creates a new MainAgentConfig instance. */
    constructor($$source: Partial<MainAgentConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MainAgentConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MainAgentConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MainAgentConfig($$parsedSource as Partial<MainAgentConfig>);
    }
}

/**
 * MainConfig represents the main opencode.json
 */
export class MainConfig {
    "$schema"?: string;
    "model"?: string;
    "small_model"?: string;
    "plugin"?: string[];
    "agent"?: { [_ in string]?: MainAgentConfig };
    "provider"?: { [_ in string]?: MainProviderConfig };
    "mcp"?: { [_ in string]?: any };

    /** Creates a new MainConfig instance. */
    constructor($$source: Partial<MainConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MainConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MainConfig {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugin" in $$parsedSource) {
            $$parsedSource["plugin"] = $$createField3_0($$parsedSource["plugin"]);
        }
        if ("agent" in $$parsedSource) {
            $$parsedSource["agent"] = $$createField4_0($$parsedSource["agent"]);
        }
        if ("provider" in $$parsedSource) {
            $$parsedSource["provider"] = $$createField5_0($$parsedSource["provider"]);
        }
        if ("mcp" in $$parsedSource) {
            $$parsedSource["mcp"] = $$createField6_0($$parsedSource["mcp"]);
        }
        return new MainConfig($$parsedSource as Partial<MainConfig>);
    }
}

/**
 * MainProviderConfig represents a provider configuration in the main config
 */
export class MainProviderConfig {
    "options"?: { [_ in string]?: any };

    /** Creates a new MainProviderConfig instance. */
    constructor($$source: Partial<MainProviderConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MainProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MainProviderConfig {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField0_0($$parsedSource["options"]);
        }
        return new MainProviderConfig($$parsedSource as Partial<MainProviderConfig>);
    }
}

/**
 * Preset 预设配置
 */
export class Preset {
    "orchestrator"?: AgentConfig | null;
    "oracle"?: AgentConfig | null;
    "librarian"?: AgentConfig | null;
    "explorer"?: AgentConfig | null;
    "designer"?: AgentConfig | null;
    "fixer"?: AgentConfig | null;

    /** Creates a new Preset instance. */
    constructor($$source: Partial<Preset> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preset instance from a string or object.
     */
    static createFrom($$source: any = {}): Preset {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("orchestrator" in $$parsedSource) {
            $$parsedSource["orchestrator"] = $$createField0_0($$parsedSource["orchestrator"]);
        }
        if ("oracle" in $$parsedSource) {
            $$parsedSource["oracle"] = $$createField1_0($$parsedSource["oracle"]);
        }
        if ("librarian" in $$parsedSource) {
            $$parsedSource["librarian"] = $$createField2_0($$parsedSource["librarian"]);
        }
        if ("explorer" in $$parsedSource) {
            $$parsedSource["explorer"] = $$createField3_0($$parsedSource["explorer"]);
        }
        if ("designer" in $$parsedSource) {
            $$parsedSource["designer"] = $$createField4_0($$parsedSource["designer"]);
        }
        if ("fixer" in $$parsedSource) {
            $$parsedSource["fixer"] = $$createField5_0($$parsedSource["fixer"]);
        }
        return new Preset($$parsedSource as Partial<Preset>);
    }
}

/**
 * PresetDiff 预设差异
 */
export class PresetDiff {
    "store_active": string;
    "file_active": string;
    "differences": string[];

    /** Creates a new PresetDiff instance. */
    constructor($$source: Partial<PresetDiff> = {}) {
        if (!("store_active" in $$source)) {
            this["store_active"] = "";
        }
        if (!("file_active" in $$source)) {
            this["file_active"] = "";
        }
        if (!("differences" in $$source)) {
            this["differences"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetDiff {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("differences" in $$parsedSource) {
            $$parsedSource["differences"] = $$createField2_0($$parsedSource["differences"]);
        }
        return new PresetDiff($$parsedSource as Partial<PresetDiff>);
    }
}

/**
 * PresetStoreData 持久存储结构
 */
export class PresetStoreData {
    "active_preset": string;
    "presets": { [_ in string]?: Preset | null };

    /** Creates a new PresetStoreData instance. */
    constructor($$source: Partial<PresetStoreData> = {}) {
        if (!("active_preset" in $$source)) {
            this["active_preset"] = "";
        }
        if (!("presets" in $$source)) {
            this["presets"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetStoreData instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetStoreData {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField1_0($$parsedSource["presets"]);
        }
        return new PresetStoreData($$parsedSource as Partial<PresetStoreData>);
    }
}

/**
 * SkillInfo represents a discovered skill
 */
export class SkillInfo {
    "name": string;
    "description": string;

    /**
     * "config", "plugin", or "agent"
     */
    "source": string;

    /** Creates a new SkillInfo instance. */
    constructor($$source: Partial<SkillInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo($$parsedSource as Partial<SkillInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = MainAgentConfig.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = MainProviderConfig.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = AgentConfig.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = Preset.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $$createType9);
