// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PathEntry {
    "rawPath": string;
    "path": string;
    "exists": boolean;
    "isDir": boolean;

    /** Creates a new PathEntry instance. */
    constructor($$source: Partial<PathEntry> = {}) {
        if (!("rawPath" in $$source)) {
            this["rawPath"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PathEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathEntry($$parsedSource as Partial<PathEntry>);
    }
}

export class PathProfileDTO {
    "name": string;
    "paths": string[];

    /** Creates a new PathProfileDTO instance. */
    constructor($$source: Partial<PathProfileDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathProfileDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PathProfileDTO {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField1_0($$parsedSource["paths"]);
        }
        return new PathProfileDTO($$parsedSource as Partial<PathProfileDTO>);
    }
}

export class PathResult {
    "system": (PathEntry | null)[];
    "user": (PathEntry | null)[];

    /** Creates a new PathResult instance. */
    constructor($$source: Partial<PathResult> = {}) {
        if (!("system" in $$source)) {
            this["system"] = [];
        }
        if (!("user" in $$source)) {
            this["user"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PathResult {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("system" in $$parsedSource) {
            $$parsedSource["system"] = $$createField0_0($$parsedSource["system"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        return new PathResult($$parsedSource as Partial<PathResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PathEntry.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
