// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PathEntry {
    /**
     * Creates a new PathEntry instance.
     * @param {Partial<PathEntry>} [$$source = {}] - The source object to create the PathEntry.
     */
    constructor($$source = {}) {
        if (!("rawPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rawPath"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PathEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathEntry(/** @type {Partial<PathEntry>} */($$parsedSource));
    }
}

export class PathProfileDTO {
    /**
     * Creates a new PathProfileDTO instance.
     * @param {Partial<PathProfileDTO>} [$$source = {}] - The source object to create the PathProfileDTO.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("paths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathProfileDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PathProfileDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField1_0($$parsedSource["paths"]);
        }
        return new PathProfileDTO(/** @type {Partial<PathProfileDTO>} */($$parsedSource));
    }
}

export class PathResult {
    /**
     * Creates a new PathResult instance.
     * @param {Partial<PathResult>} [$$source = {}] - The source object to create the PathResult.
     */
    constructor($$source = {}) {
        if (!("system" in $$source)) {
            /**
             * @member
             * @type {(PathEntry | null)[]}
             */
            this["system"] = [];
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {(PathEntry | null)[]}
             */
            this["user"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PathResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("system" in $$parsedSource) {
            $$parsedSource["system"] = $$createField0_0($$parsedSource["system"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        return new PathResult(/** @type {Partial<PathResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PathEntry.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
