// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("baseDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class SDKInfo {
    /**
     * Creates a new SDKInfo instance.
     * @param {Partial<SDKInfo>} [$$source = {}] - The source object to create the SDKInfo.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {SDKType}
             */
            this["type"] = SDKType.$zero;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {SDKVersion[]}
             */
            this["installed"] = [];
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SDKInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SDKInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("installed" in $$parsedSource) {
            $$parsedSource["installed"] = $$createField3_0($$parsedSource["installed"]);
        }
        return new SDKInfo(/** @type {Partial<SDKInfo>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const SDKType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SDKGo: "go",
    SDKNode: "nodejs",
    SDKJava: "java",
};

export class SDKVersion {
    /**
     * Creates a new SDKVersion instance.
     * @param {Partial<SDKVersion>} [$$source = {}] - The source object to create the SDKVersion.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SDKVersion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SDKVersion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SDKVersion(/** @type {Partial<SDKVersion>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SDKVersion.createFrom;
const $$createType1 = $Create.Array($$createType0);
