// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    "baseDir": string;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("baseDir" in $$source)) {
            this["baseDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class SDKInfo {
    "type": SDKType;
    "name": string;
    "icon": string;
    "installed": SDKVersion[];
    "current": string;

    /** Creates a new SDKInfo instance. */
    constructor($$source: Partial<SDKInfo> = {}) {
        if (!("type" in $$source)) {
            this["type"] = SDKType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = [];
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SDKInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SDKInfo {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("installed" in $$parsedSource) {
            $$parsedSource["installed"] = $$createField3_0($$parsedSource["installed"]);
        }
        return new SDKInfo($$parsedSource as Partial<SDKInfo>);
    }
}

export enum SDKType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SDKGo = "go",
    SDKNode = "nodejs",
    SDKJava = "java",
};

export class SDKVersion {
    "version": string;
    "path": string;
    "active": boolean;

    /** Creates a new SDKVersion instance. */
    constructor($$source: Partial<SDKVersion> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SDKVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): SDKVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SDKVersion($$parsedSource as Partial<SDKVersion>);
    }
}

// Private type creation functions
const $$createType0 = SDKVersion.createFrom;
const $$createType1 = $Create.Array($$createType0);
