// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EnvResult holds user and system environment variables.
 */
export class EnvResult {
    "system": EnvVar[];
    "user": EnvVar[];

    /** Creates a new EnvResult instance. */
    constructor($$source: Partial<EnvResult> = {}) {
        if (!("system" in $$source)) {
            this["system"] = [];
        }
        if (!("user" in $$source)) {
            this["user"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvResult instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvResult {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("system" in $$parsedSource) {
            $$parsedSource["system"] = $$createField0_0($$parsedSource["system"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        return new EnvResult($$parsedSource as Partial<EnvResult>);
    }
}

/**
 * EnvVar represents a single environment variable.
 */
export class EnvVar {
    "name": string;
    "value": string;

    /**
     * true for the PATH variable
     */
    "isPath": boolean;

    /** Creates a new EnvVar instance. */
    constructor($$source: Partial<EnvVar> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("isPath" in $$source)) {
            this["isPath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvVar instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvVar {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvVar($$parsedSource as Partial<EnvVar>);
    }
}

// Private type creation functions
const $$createType0 = EnvVar.createFrom;
const $$createType1 = $Create.Array($$createType0);
