// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EnvResult holds user and system environment variables.
 */
export class EnvResult {
    /**
     * Creates a new EnvResult instance.
     * @param {Partial<EnvResult>} [$$source = {}] - The source object to create the EnvResult.
     */
    constructor($$source = {}) {
        if (!("system" in $$source)) {
            /**
             * @member
             * @type {EnvVar[]}
             */
            this["system"] = [];
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {EnvVar[]}
             */
            this["user"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("system" in $$parsedSource) {
            $$parsedSource["system"] = $$createField0_0($$parsedSource["system"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        return new EnvResult(/** @type {Partial<EnvResult>} */($$parsedSource));
    }
}

/**
 * EnvVar represents a single environment variable.
 */
export class EnvVar {
    /**
     * Creates a new EnvVar instance.
     * @param {Partial<EnvVar>} [$$source = {}] - The source object to create the EnvVar.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("isPath" in $$source)) {
            /**
             * true for the PATH variable
             * @member
             * @type {boolean}
             */
            this["isPath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvVar instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvVar}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvVar(/** @type {Partial<EnvVar>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = EnvVar.createFrom;
const $$createType1 = $Create.Array($$createType0);
