// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as envvars$0 from "./internal/envvars/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as opencode$0 from "./internal/opencode/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pathenv$0 from "./internal/pathenv/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime$0 from "./internal/runtime/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} profileName
 * @returns {$CancellablePromise<void>}
 */
export function ApplyPathProfile(profileName) {
    return $Call.ByID(1043816161, profileName);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function CleanInvalidUserPaths() {
    return $Call.ByID(2795976854).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ClearScriptLogs(id) {
    return $Call.ByID(985373930, id);
}

/**
 * @param {string} name
 * @param {number | null} parentID
 * @returns {$CancellablePromise<void>}
 */
export function CreateCategory(name, parentID) {
    return $Call.ByID(4163536593, name, parentID);
}

/**
 * @param {models$0.EntryDTO} dto
 * @returns {$CancellablePromise<void>}
 */
export function CreateEntry(dto) {
    return $Call.ByID(1737588083, dto);
}

/**
 * @param {string} name
 * @param {string} notes
 * @returns {$CancellablePromise<models$0.ProjectDTO>}
 */
export function CreateProject(name, notes) {
    return $Call.ByID(969543070, name, notes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} name
 * @param {string} command
 * @param {string} workDir
 * @param {string} envVars
 * @param {string} notes
 * @param {boolean} elevated
 * @param {boolean} keepWindow
 * @param {number} projectID
 * @returns {$CancellablePromise<models$0.ScriptDTO>}
 */
export function CreateScript(name, command, workDir, envVars, notes, elevated, keepWindow, projectID) {
    return $Call.ByID(2633019146, name, command, workDir, envVars, notes, elevated, keepWindow, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} name
 * @param {string} color
 * @returns {$CancellablePromise<void>}
 */
export function CreateTag(name, color) {
    return $Call.ByID(3527446643, name, color);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCategory(id) {
    return $Call.ByID(988551738, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEntry(id) {
    return $Call.ByID(3442753994, id);
}

/**
 * @param {string} name
 * @param {boolean} system
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEnvVar(name, system) {
    return $Call.ByID(4217620542, name, system);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeletePathProfile(name) {
    return $Call.ByID(2589599762, name);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProject(id) {
    return $Call.ByID(3379369923, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteScript(id) {
    return $Call.ByID(2965526601, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTag(id) {
    return $Call.ByID(4252857114, id);
}

/**
 * @returns {$CancellablePromise<opencode$0.AppendPromptDiff[]>}
 */
export function DiffAppendPrompts() {
    return $Call.ByID(2614948957).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<opencode$0.PresetDiff | null>}
 */
export function DiffPresets() {
    return $Call.ByID(1108344750).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DisableHello() {
    return $Call.ByID(3075865513);
}

/**
 * @param {string} value
 * @returns {$CancellablePromise<string>}
 */
export function ExpandEnvValue(value) {
    return $Call.ByID(1336177801, value);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function FetchAvailableModels() {
    return $Call.ByID(2467726340).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} sdkType
 * @param {boolean} force
 * @returns {$CancellablePromise<string[]>}
 */
export function FetchAvailableVersions(sdkType, force) {
    return $Call.ByID(3864014919, sdkType, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.MCPSkillResult>}
 */
export function FetchMCPSkills() {
    return $Call.ByID(734296211).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ForceRefreshModels() {
    return $Call.ByID(2700008581).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} agentName
 * @returns {$CancellablePromise<string>}
 */
export function GetAppendPromptPath(agentName) {
    return $Call.ByID(2214829246, agentName);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAppendPromptStoreDir() {
    return $Call.ByID(927971293);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetAppendPromptStoreStats() {
    return $Call.ByID(2947573853);
}

/**
 * @returns {$CancellablePromise<(models$0.CategoryDTO | null)[]>}
 */
export function GetCategoryTree() {
    return $Call.ByID(4284198303).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCloseBehavior() {
    return $Call.ByID(1662826935);
}

/**
 * @param {number | null} categoryID
 * @param {number | null} tagID
 * @returns {$CancellablePromise<(models$0.EntryDTO | null)[]>}
 */
export function GetEntries(categoryID, tagID) {
    return $Call.ByID(825412789, categoryID, tagID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} name
 * @param {boolean} system
 * @returns {$CancellablePromise<string>}
 */
export function GetEnvVar(name, system) {
    return $Call.ByID(2283769791, name, system);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetHelloAvailability() {
    return $Call.ByID(2709263366);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetHelloCredential() {
    return $Call.ByID(3823851016).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetMainConfigPath() {
    return $Call.ByID(3358422431);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetOpenCodeAgentColors() {
    return $Call.ByID(1129207847).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetOpenCodeAgentLabels() {
    return $Call.ByID(3353751836).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetOpenCodeAgentNames() {
    return $Call.ByID(1822280573).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<opencode$0.PresetStoreData | null>}
 */
export function GetOpenCodeConfig() {
    return $Call.ByID(3091624868).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetOpenCodeConfigPath() {
    return $Call.ByID(1985929075);
}

/**
 * @returns {$CancellablePromise<opencode$0.MCPInfo[]>}
 */
export function GetOpenCodeMCPs() {
    return $Call.ByID(3222510959).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<opencode$0.SkillInfo[]>}
 */
export function GetOpenCodeSkills() {
    return $Call.ByID(3755031352).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<string>}
 */
export function GetPassword(id) {
    return $Call.ByID(2090530822, id);
}

/**
 * @returns {$CancellablePromise<(pathenv$0.PathEntry | null)[]>}
 */
export function GetPathEntries() {
    return $Call.ByID(1326049304).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @returns {$CancellablePromise<pathenv$0.PathResult | null>}
 */
export function GetPathResult() {
    return $Call.ByID(507565777).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * @returns {$CancellablePromise<runtime$0.Config | null>}
 */
export function GetRuntimeConfig() {
    return $Call.ByID(1952287779).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.LogLineDTO[]>}
 */
export function GetScriptLogs(id) {
    return $Call.ByID(3999182811, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.ScriptStatusDTO>}
 */
export function GetScriptStatus(id) {
    return $Call.ByID(3622102042, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @returns {$CancellablePromise<(models$0.TagDTO | null)[]>}
 */
export function GetTags() {
    return $Call.ByID(4196874850).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(542966029);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function ImportAppendPromptsFromFiles() {
    return $Call.ByID(3267586126);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ImportPresetsFromConfig() {
    return $Call.ByID(892274750);
}

/**
 * @param {string} sdkType
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function InstallSDK(sdkType, version) {
    return $Call.ByID(3176650060, sdkType, version);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsHelloEnabled() {
    return $Call.ByID(48186200);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsInitialized() {
    return $Call.ByID(1774547845);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsUnlocked() {
    return $Call.ByID(4148661316);
}

/**
 * @returns {$CancellablePromise<envvars$0.EnvResult | null>}
 */
export function ListEnvVars() {
    return $Call.ByID(3527054334).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * @returns {$CancellablePromise<pathenv$0.PathProfileDTO[]>}
 */
export function ListPathProfiles() {
    return $Call.ByID(3345808340).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.ProjectDTO[]>}
 */
export function ListProjects() {
    return $Call.ByID(2721360259).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * @returns {$CancellablePromise<runtime$0.SDKInfo[]>}
 */
export function ListSDKs() {
    return $Call.ByID(2379340916).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.ScriptDTO[]>}
 */
export function ListScripts() {
    return $Call.ByID(3467580111).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Lock() {
    return $Call.ByID(253832250);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenInExplorer(path) {
    return $Call.ByID(1095611661, path);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenOpenCodeConfigDir() {
    return $Call.ByID(431491601);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenTerminal(dir) {
    return $Call.ByID(2247958725, dir);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenWindowsHelloSettings() {
    return $Call.ByID(3868614499);
}

/**
 * @param {string} profileName
 * @returns {$CancellablePromise<string[]>}
 */
export function PreviewMergeProfile(profileName) {
    return $Call.ByID(666475966, profileName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(3730234565);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function ReadAllAppendPrompts() {
    return $Call.ByID(3286145931).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} agentName
 * @returns {$CancellablePromise<string>}
 */
export function ReadAppendPrompt(agentName) {
    return $Call.ByID(1330307399, agentName);
}

/**
 * @returns {$CancellablePromise<opencode$0.MainConfig | null>}
 */
export function ReadMainConfig() {
    return $Call.ByID(4012197422).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenamePathProfile(oldName, newName) {
    return $Call.ByID(1396416377, oldName, newName);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function RestartScript(id) {
    return $Call.ByID(2434307231, id);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function RestoreAppendPrompts() {
    return $Call.ByID(1646315600);
}

/**
 * @param {opencode$0.MainConfig | null} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveMainConfig(cfg) {
    return $Call.ByID(947960335, cfg);
}

/**
 * @param {opencode$0.PresetStoreData | null} store
 * @returns {$CancellablePromise<void>}
 */
export function SaveOpenCodeConfig(store) {
    return $Call.ByID(755107759, store);
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function SavePathEntries(paths) {
    return $Call.ByID(3238994861, paths);
}

/**
 * @param {pathenv$0.PathProfileDTO} dto
 * @returns {$CancellablePromise<void>}
 */
export function SavePathProfile(dto) {
    return $Call.ByID(4229876296, dto);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(1735672136);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectScriptFile() {
    return $Call.ByID(1719644492);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(4256893662, app);
}

/**
 * @param {string} behavior
 * @returns {$CancellablePromise<void>}
 */
export function SetCloseBehavior(behavior) {
    return $Call.ByID(1838468491, behavior);
}

/**
 * @param {string} name
 * @param {string} value
 * @param {boolean} system
 * @returns {$CancellablePromise<void>}
 */
export function SetEnvVar(name, value, system) {
    return $Call.ByID(193721515, name, value, system);
}

/**
 * @param {application$0.WebviewWindow | null} window
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(window) {
    return $Call.ByID(843697430, window);
}

/**
 * @param {string} baseDir
 * @returns {$CancellablePromise<void>}
 */
export function SetRuntimeConfig(baseDir) {
    return $Call.ByID(1295833711, baseDir);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetupHello() {
    return $Call.ByID(3020273806);
}

/**
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function SetupMasterKey(password) {
    return $Call.ByID(2755384515, password);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function ShouldBypassCloseConfirm() {
    return $Call.ByID(1909950370);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function StartScript(id) {
    return $Call.ByID(1227347632, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function StopScript(id) {
    return $Call.ByID(3612390418, id);
}

/**
 * @param {string} credId
 * @returns {$CancellablePromise<void>}
 */
export function StoreHelloCredential(credId) {
    return $Call.ByID(2310347155, credId);
}

/**
 * @param {string} sdkType
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function SwitchSDK(sdkType, version) {
    return $Call.ByID(1305995871, sdkType, version);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SyncPresetsToConfig() {
    return $Call.ByID(3848391041);
}

/**
 * @param {string} sdkType
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function UninstallSDK(sdkType, version) {
    return $Call.ByID(743454279, sdkType, version);
}

/**
 * @param {string} password
 * @returns {$CancellablePromise<boolean>}
 */
export function Unlock(password) {
    return $Call.ByID(1127700317, password);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function UnlockWithHello() {
    return $Call.ByID(3631940815);
}

/**
 * @param {number} id
 * @param {string} name
 * @param {number | null} parentID
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCategory(id, name, parentID) {
    return $Call.ByID(2178518964, id, name, parentID);
}

/**
 * @param {models$0.EntryDTO} dto
 * @returns {$CancellablePromise<void>}
 */
export function UpdateEntry(dto) {
    return $Call.ByID(2925690800, dto);
}

/**
 * @param {number} id
 * @param {string} name
 * @param {string} notes
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProject(id, name, notes) {
    return $Call.ByID(1522260689, id, name, notes);
}

/**
 * @param {number} id
 * @param {string} name
 * @param {string} command
 * @param {string} workDir
 * @param {string} envVars
 * @param {string} notes
 * @param {boolean} elevated
 * @param {boolean} keepWindow
 * @param {number} projectID
 * @returns {$CancellablePromise<void>}
 */
export function UpdateScript(id, name, command, workDir, envVars, notes, elevated, keepWindow, projectID) {
    return $Call.ByID(3137072103, id, name, command, workDir, envVars, notes, elevated, keepWindow, projectID);
}

/**
 * @param {number} id
 * @param {string} name
 * @param {string} color
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTag(id, name, color) {
    return $Call.ByID(3262886260, id, name, color);
}

/**
 * @param {string} agentName
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteAppendPrompt(agentName, content) {
    return $Call.ByID(2569088754, agentName, content);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.ProjectDTO.createFrom;
const $$createType2 = models$0.ScriptDTO.createFrom;
const $$createType3 = opencode$0.AppendPromptDiff.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = opencode$0.PresetDiff.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.MCPSkillResult.createFrom;
const $$createType8 = models$0.CategoryDTO.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = models$0.EntryDTO.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
const $$createType15 = opencode$0.PresetStoreData.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = opencode$0.MCPInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = opencode$0.SkillInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = pathenv$0.PathEntry.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = pathenv$0.PathResult.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = runtime$0.Config.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = models$0.LogLineDTO.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = models$0.ScriptStatusDTO.createFrom;
const $$createType31 = models$0.TagDTO.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = envvars$0.EnvResult.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = pathenv$0.PathProfileDTO.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = $Create.Array($$createType1);
const $$createType39 = runtime$0.SDKInfo.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = $Create.Array($$createType2);
const $$createType42 = opencode$0.MainConfig.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
