// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as envvars$0 from "./internal/envvars/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as opencode$0 from "./internal/opencode/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pathenv$0 from "./internal/pathenv/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime$0 from "./internal/runtime/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyPathProfile(profileName: string): $CancellablePromise<void> {
    return $Call.ByID(1043816161, profileName);
}

export function CleanInvalidUserPaths(): $CancellablePromise<string[]> {
    return $Call.ByID(2795976854).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ClearScriptLogs(id: number): $CancellablePromise<void> {
    return $Call.ByID(985373930, id);
}

export function CreateCategory(name: string, parentID: number | null): $CancellablePromise<void> {
    return $Call.ByID(4163536593, name, parentID);
}

export function CreateEntry(dto: models$0.EntryDTO): $CancellablePromise<void> {
    return $Call.ByID(1737588083, dto);
}

export function CreateProject(name: string, notes: string): $CancellablePromise<models$0.ProjectDTO> {
    return $Call.ByID(969543070, name, notes).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateScript(name: string, command: string, workDir: string, envVars: string, notes: string, elevated: boolean, keepWindow: boolean, projectID: number): $CancellablePromise<models$0.ScriptDTO> {
    return $Call.ByID(2633019146, name, command, workDir, envVars, notes, elevated, keepWindow, projectID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreateTag(name: string, color: string): $CancellablePromise<void> {
    return $Call.ByID(3527446643, name, color);
}

export function DeleteCategory(id: number): $CancellablePromise<void> {
    return $Call.ByID(988551738, id);
}

export function DeleteEntry(id: number): $CancellablePromise<void> {
    return $Call.ByID(3442753994, id);
}

export function DeleteEnvVar(name: string, system: boolean): $CancellablePromise<void> {
    return $Call.ByID(4217620542, name, system);
}

export function DeletePathProfile(name: string): $CancellablePromise<void> {
    return $Call.ByID(2589599762, name);
}

export function DeleteProject(id: number): $CancellablePromise<void> {
    return $Call.ByID(3379369923, id);
}

export function DeleteScript(id: number): $CancellablePromise<void> {
    return $Call.ByID(2965526601, id);
}

export function DeleteTag(id: number): $CancellablePromise<void> {
    return $Call.ByID(4252857114, id);
}

export function DiffAppendPrompts(): $CancellablePromise<opencode$0.AppendPromptDiff[]> {
    return $Call.ByID(2614948957).then(($result: any) => {
        return $$createType4($result);
    });
}

export function DiffPresets(): $CancellablePromise<opencode$0.PresetDiff | null> {
    return $Call.ByID(1108344750).then(($result: any) => {
        return $$createType6($result);
    });
}

export function DisableHello(): $CancellablePromise<void> {
    return $Call.ByID(3075865513);
}

export function ExpandEnvValue(value: string): $CancellablePromise<string> {
    return $Call.ByID(1336177801, value);
}

export function FetchAvailableModels(): $CancellablePromise<string[]> {
    return $Call.ByID(2467726340).then(($result: any) => {
        return $$createType0($result);
    });
}

export function FetchAvailableVersions(sdkType: string, force: boolean): $CancellablePromise<string[]> {
    return $Call.ByID(3864014919, sdkType, force).then(($result: any) => {
        return $$createType0($result);
    });
}

export function FetchMCPSkills(): $CancellablePromise<$models.MCPSkillResult> {
    return $Call.ByID(734296211).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ForceRefreshModels(): $CancellablePromise<string[]> {
    return $Call.ByID(2700008581).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAppendPromptPath(agentName: string): $CancellablePromise<string> {
    return $Call.ByID(2214829246, agentName);
}

export function GetAppendPromptStoreDir(): $CancellablePromise<string> {
    return $Call.ByID(927971293);
}

export function GetAppendPromptStoreStats(): $CancellablePromise<number> {
    return $Call.ByID(2947573853);
}

export function GetCategoryTree(): $CancellablePromise<(models$0.CategoryDTO | null)[]> {
    return $Call.ByID(4284198303).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetCloseBehavior(): $CancellablePromise<string> {
    return $Call.ByID(1662826935);
}

export function GetEntries(categoryID: number | null, tagID: number | null): $CancellablePromise<(models$0.EntryDTO | null)[]> {
    return $Call.ByID(825412789, categoryID, tagID).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetEnvVar(name: string, system: boolean): $CancellablePromise<string> {
    return $Call.ByID(2283769791, name, system);
}

export function GetHelloAvailability(): $CancellablePromise<string> {
    return $Call.ByID(2709263366);
}

export function GetHelloCredential(): $CancellablePromise<string> {
    return $Call.ByID(3823851016).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

export function GetMainConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(3358422431);
}

export function GetOpenCodeAgentColors(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1129207847).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetOpenCodeAgentLabels(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(3353751836).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetOpenCodeAgentNames(): $CancellablePromise<string[]> {
    return $Call.ByID(1822280573).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetOpenCodeConfig(): $CancellablePromise<opencode$0.PresetStoreData | null> {
    return $Call.ByID(3091624868).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetOpenCodeConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(1985929075);
}

export function GetOpenCodeMCPs(): $CancellablePromise<opencode$0.MCPInfo[]> {
    return $Call.ByID(3222510959).then(($result: any) => {
        return $$createType18($result);
    });
}

export function GetOpenCodeSkills(): $CancellablePromise<opencode$0.SkillInfo[]> {
    return $Call.ByID(3755031352).then(($result: any) => {
        return $$createType20($result);
    });
}

export function GetPassword(id: number): $CancellablePromise<string> {
    return $Call.ByID(2090530822, id);
}

export function GetPathEntries(): $CancellablePromise<(pathenv$0.PathEntry | null)[]> {
    return $Call.ByID(1326049304).then(($result: any) => {
        return $$createType23($result);
    });
}

export function GetPathResult(): $CancellablePromise<pathenv$0.PathResult | null> {
    return $Call.ByID(507565777).then(($result: any) => {
        return $$createType25($result);
    });
}

export function GetRuntimeConfig(): $CancellablePromise<runtime$0.Config | null> {
    return $Call.ByID(1952287779).then(($result: any) => {
        return $$createType27($result);
    });
}

export function GetScriptLogs(id: number): $CancellablePromise<models$0.LogLineDTO[]> {
    return $Call.ByID(3999182811, id).then(($result: any) => {
        return $$createType29($result);
    });
}

export function GetScriptStatus(id: number): $CancellablePromise<models$0.ScriptStatusDTO> {
    return $Call.ByID(3622102042, id).then(($result: any) => {
        return $$createType30($result);
    });
}

export function GetTags(): $CancellablePromise<(models$0.TagDTO | null)[]> {
    return $Call.ByID(4196874850).then(($result: any) => {
        return $$createType33($result);
    });
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(542966029);
}

export function ImportAppendPromptsFromFiles(): $CancellablePromise<number> {
    return $Call.ByID(3267586126);
}

export function ImportPresetsFromConfig(): $CancellablePromise<void> {
    return $Call.ByID(892274750);
}

export function InstallSDK(sdkType: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(3176650060, sdkType, version);
}

export function IsHelloEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(48186200);
}

export function IsInitialized(): $CancellablePromise<boolean> {
    return $Call.ByID(1774547845);
}

export function IsUnlocked(): $CancellablePromise<boolean> {
    return $Call.ByID(4148661316);
}

export function ListEnvVars(): $CancellablePromise<envvars$0.EnvResult | null> {
    return $Call.ByID(3527054334).then(($result: any) => {
        return $$createType35($result);
    });
}

export function ListPathProfiles(): $CancellablePromise<pathenv$0.PathProfileDTO[]> {
    return $Call.ByID(3345808340).then(($result: any) => {
        return $$createType37($result);
    });
}

export function ListProjects(): $CancellablePromise<models$0.ProjectDTO[]> {
    return $Call.ByID(2721360259).then(($result: any) => {
        return $$createType38($result);
    });
}

export function ListSDKs(): $CancellablePromise<runtime$0.SDKInfo[]> {
    return $Call.ByID(2379340916).then(($result: any) => {
        return $$createType40($result);
    });
}

export function ListScripts(): $CancellablePromise<models$0.ScriptDTO[]> {
    return $Call.ByID(3467580111).then(($result: any) => {
        return $$createType41($result);
    });
}

export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(253832250);
}

export function OpenInExplorer(path: string): $CancellablePromise<void> {
    return $Call.ByID(1095611661, path);
}

export function OpenOpenCodeConfigDir(): $CancellablePromise<void> {
    return $Call.ByID(431491601);
}

export function OpenTerminal(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2247958725, dir);
}

export function OpenWindowsHelloSettings(): $CancellablePromise<void> {
    return $Call.ByID(3868614499);
}

export function PreviewMergeProfile(profileName: string): $CancellablePromise<string[]> {
    return $Call.ByID(666475966, profileName).then(($result: any) => {
        return $$createType0($result);
    });
}

export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(3730234565);
}

export function ReadAllAppendPrompts(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(3286145931).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ReadAppendPrompt(agentName: string): $CancellablePromise<string> {
    return $Call.ByID(1330307399, agentName);
}

export function ReadMainConfig(): $CancellablePromise<opencode$0.MainConfig | null> {
    return $Call.ByID(4012197422).then(($result: any) => {
        return $$createType43($result);
    });
}

export function RenamePathProfile(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1396416377, oldName, newName);
}

export function RestartScript(id: number): $CancellablePromise<void> {
    return $Call.ByID(2434307231, id);
}

export function RestoreAppendPrompts(): $CancellablePromise<number> {
    return $Call.ByID(1646315600);
}

export function SaveMainConfig(cfg: opencode$0.MainConfig | null): $CancellablePromise<void> {
    return $Call.ByID(947960335, cfg);
}

export function SaveOpenCodeConfig(store: opencode$0.PresetStoreData | null): $CancellablePromise<void> {
    return $Call.ByID(755107759, store);
}

export function SavePathEntries(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3238994861, paths);
}

export function SavePathProfile(dto: pathenv$0.PathProfileDTO): $CancellablePromise<void> {
    return $Call.ByID(4229876296, dto);
}

export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1735672136);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4256893662, app);
}

export function SetCloseBehavior(behavior: string): $CancellablePromise<void> {
    return $Call.ByID(1838468491, behavior);
}

export function SetEnvVar(name: string, value: string, system: boolean): $CancellablePromise<void> {
    return $Call.ByID(193721515, name, value, system);
}

export function SetMainWindow(window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(843697430, window);
}

export function SetRuntimeConfig(baseDir: string): $CancellablePromise<void> {
    return $Call.ByID(1295833711, baseDir);
}

export function SetupHello(): $CancellablePromise<void> {
    return $Call.ByID(3020273806);
}

export function SetupMasterKey(password: string): $CancellablePromise<void> {
    return $Call.ByID(2755384515, password);
}

export function ShouldBypassCloseConfirm(): $CancellablePromise<boolean> {
    return $Call.ByID(1909950370);
}

export function StartScript(id: number): $CancellablePromise<void> {
    return $Call.ByID(1227347632, id);
}

export function StopScript(id: number): $CancellablePromise<void> {
    return $Call.ByID(3612390418, id);
}

export function StoreHelloCredential(credId: string): $CancellablePromise<void> {
    return $Call.ByID(2310347155, credId);
}

export function SwitchSDK(sdkType: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(1305995871, sdkType, version);
}

export function SyncPresetsToConfig(): $CancellablePromise<void> {
    return $Call.ByID(3848391041);
}

export function UninstallSDK(sdkType: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(743454279, sdkType, version);
}

export function Unlock(password: string): $CancellablePromise<boolean> {
    return $Call.ByID(1127700317, password);
}

export function UnlockWithHello(): $CancellablePromise<boolean> {
    return $Call.ByID(3631940815);
}

export function UpdateCategory(id: number, name: string, parentID: number | null): $CancellablePromise<void> {
    return $Call.ByID(2178518964, id, name, parentID);
}

export function UpdateEntry(dto: models$0.EntryDTO): $CancellablePromise<void> {
    return $Call.ByID(2925690800, dto);
}

export function UpdateProject(id: number, name: string, notes: string): $CancellablePromise<void> {
    return $Call.ByID(1522260689, id, name, notes);
}

export function UpdateScript(id: number, name: string, command: string, workDir: string, envVars: string, notes: string, elevated: boolean, keepWindow: boolean, projectID: number): $CancellablePromise<void> {
    return $Call.ByID(3137072103, id, name, command, workDir, envVars, notes, elevated, keepWindow, projectID);
}

export function UpdateTag(id: number, name: string, color: string): $CancellablePromise<void> {
    return $Call.ByID(3262886260, id, name, color);
}

export function WriteAppendPrompt(agentName: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2569088754, agentName, content);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.ProjectDTO.createFrom;
const $$createType2 = models$0.ScriptDTO.createFrom;
const $$createType3 = opencode$0.AppendPromptDiff.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = opencode$0.PresetDiff.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.MCPSkillResult.createFrom;
const $$createType8 = models$0.CategoryDTO.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = models$0.EntryDTO.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
const $$createType15 = opencode$0.PresetStoreData.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = opencode$0.MCPInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = opencode$0.SkillInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = pathenv$0.PathEntry.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = pathenv$0.PathResult.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = runtime$0.Config.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = models$0.LogLineDTO.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = models$0.ScriptStatusDTO.createFrom;
const $$createType31 = models$0.TagDTO.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = envvars$0.EnvResult.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = pathenv$0.PathProfileDTO.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = $Create.Array($$createType1);
const $$createType39 = runtime$0.SDKInfo.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = $Create.Array($$createType2);
const $$createType42 = opencode$0.MainConfig.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
