// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as opencode$0 from "./internal/opencode/models.js";

/**
 * BatchStartFailure 单个脚本启动失败信息
 */
export class BatchStartFailure {
    /**
     * Creates a new BatchStartFailure instance.
     * @param {Partial<BatchStartFailure>} [$$source = {}] - The source object to create the BatchStartFailure.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchStartFailure instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchStartFailure}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchStartFailure(/** @type {Partial<BatchStartFailure>} */($$parsedSource));
    }
}

/**
 * BatchStartResult 批量启动结果
 */
export class BatchStartResult {
    /**
     * Creates a new BatchStartResult instance.
     * @param {Partial<BatchStartResult>} [$$source = {}] - The source object to create the BatchStartResult.
     */
    constructor($$source = {}) {
        if (!("startedIds" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["startedIds"] = [];
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {BatchStartFailure[]}
             */
            this["failed"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchStartResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchStartResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("startedIds" in $$parsedSource) {
            $$parsedSource["startedIds"] = $$createField0_0($$parsedSource["startedIds"]);
        }
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField1_0($$parsedSource["failed"]);
        }
        return new BatchStartResult(/** @type {Partial<BatchStartResult>} */($$parsedSource));
    }
}

/**
 * BatchStopResult 批量停止结果
 */
export class BatchStopResult {
    /**
     * Creates a new BatchStopResult instance.
     * @param {Partial<BatchStopResult>} [$$source = {}] - The source object to create the BatchStopResult.
     */
    constructor($$source = {}) {
        if (!("stoppedIds" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["stoppedIds"] = [];
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {BatchStartFailure[]}
             */
            this["failed"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchStopResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchStopResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stoppedIds" in $$parsedSource) {
            $$parsedSource["stoppedIds"] = $$createField0_0($$parsedSource["stoppedIds"]);
        }
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField1_0($$parsedSource["failed"]);
        }
        return new BatchStopResult(/** @type {Partial<BatchStopResult>} */($$parsedSource));
    }
}

export class MCPSkillResult {
    /**
     * Creates a new MCPSkillResult instance.
     * @param {Partial<MCPSkillResult>} [$$source = {}] - The source object to create the MCPSkillResult.
     */
    constructor($$source = {}) {
        if (!("mcps" in $$source)) {
            /**
             * @member
             * @type {opencode$0.MCPInfo[]}
             */
            this["mcps"] = [];
        }
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {opencode$0.SkillInfo[]}
             */
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPSkillResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MCPSkillResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mcps" in $$parsedSource) {
            $$parsedSource["mcps"] = $$createField0_0($$parsedSource["mcps"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField1_0($$parsedSource["skills"]);
        }
        return new MCPSkillResult(/** @type {Partial<MCPSkillResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = BatchStartFailure.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = opencode$0.MCPInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = opencode$0.SkillInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
