// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as opencode$0 from "./internal/opencode/models.js";

export class MCPSkillResult {
    "mcps": opencode$0.MCPInfo[];
    "skills": opencode$0.SkillInfo[];

    /** Creates a new MCPSkillResult instance. */
    constructor($$source: Partial<MCPSkillResult> = {}) {
        if (!("mcps" in $$source)) {
            this["mcps"] = [];
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPSkillResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPSkillResult {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mcps" in $$parsedSource) {
            $$parsedSource["mcps"] = $$createField0_0($$parsedSource["mcps"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField1_0($$parsedSource["skills"]);
        }
        return new MCPSkillResult($$parsedSource as Partial<MCPSkillResult>);
    }
}

// Private type creation functions
const $$createType0 = opencode$0.MCPInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = opencode$0.SkillInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
