// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as opencode$0 from "./internal/opencode/models.js";

export class MCPSkillResult {
    /**
     * Creates a new MCPSkillResult instance.
     * @param {Partial<MCPSkillResult>} [$$source = {}] - The source object to create the MCPSkillResult.
     */
    constructor($$source = {}) {
        if (!("mcps" in $$source)) {
            /**
             * @member
             * @type {opencode$0.MCPInfo[]}
             */
            this["mcps"] = [];
        }
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {opencode$0.SkillInfo[]}
             */
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPSkillResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MCPSkillResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mcps" in $$parsedSource) {
            $$parsedSource["mcps"] = $$createField0_0($$parsedSource["mcps"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField1_0($$parsedSource["skills"]);
        }
        return new MCPSkillResult(/** @type {Partial<MCPSkillResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = opencode$0.MCPInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = opencode$0.SkillInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
