// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CategoryDTO 分类传输对象（含树形 children）
 */
export class CategoryDTO {
    "id": number;
    "name": string;
    "parentId": number | null;
    "icon": string;
    "order": number;
    "children": (CategoryDTO | null)[];

    /** Creates a new CategoryDTO instance. */
    constructor($$source: Partial<CategoryDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = null;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CategoryDTO {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new CategoryDTO($$parsedSource as Partial<CategoryDTO>);
    }
}

/**
 * EntryDTO 前端交互的数据传输对象
 */
export class EntryDTO {
    "id": number;
    "title": string;
    "username": string;
    "password"?: string;
    "url": string;
    "categoryId": number | null;
    "categoryName": string;
    "tagIds": number[];
    "tags": TagDTO[];
    "notes": string;

    /** Creates a new EntryDTO instance. */
    constructor($$source: Partial<EntryDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("categoryId" in $$source)) {
            this["categoryId"] = null;
        }
        if (!("categoryName" in $$source)) {
            this["categoryName"] = "";
        }
        if (!("tagIds" in $$source)) {
            this["tagIds"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryDTO {
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tagIds" in $$parsedSource) {
            $$parsedSource["tagIds"] = $$createField7_0($$parsedSource["tagIds"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new EntryDTO($$parsedSource as Partial<EntryDTO>);
    }
}

/**
 * LogLineDTO 日志行传输对象
 */
export class LogLineDTO {
    "id": number;
    "scriptId": number;
    "text": string;

    /**
     * stdout or stderr
     */
    "source": string;
    "timestamp": string;

    /** Creates a new LogLineDTO instance. */
    constructor($$source: Partial<LogLineDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("scriptId" in $$source)) {
            this["scriptId"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLineDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LogLineDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLineDTO($$parsedSource as Partial<LogLineDTO>);
    }
}

/**
 * ProjectDTO 前端传输对象
 */
export class ProjectDTO {
    "id": number;
    "name": string;
    "notes": string;
    "order": number;
    "scriptCount": number;

    /** Creates a new ProjectDTO instance. */
    constructor($$source: Partial<ProjectDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }
        if (!("scriptCount" in $$source)) {
            this["scriptCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectDTO($$parsedSource as Partial<ProjectDTO>);
    }
}

/**
 * ScriptDTO 前端传输对象
 */
export class ScriptDTO {
    "id": number;
    "name": string;
    "command": string;
    "workDir": string;
    "envVars": string;
    "notes": string;
    "elevated": boolean;
    "keepWindow": boolean;
    "projectId": number | null;
    "projectName": string;
    "createdAt": string;

    /** Creates a new ScriptDTO instance. */
    constructor($$source: Partial<ScriptDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("workDir" in $$source)) {
            this["workDir"] = "";
        }
        if (!("envVars" in $$source)) {
            this["envVars"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("elevated" in $$source)) {
            this["elevated"] = false;
        }
        if (!("keepWindow" in $$source)) {
            this["keepWindow"] = false;
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = null;
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptDTO($$parsedSource as Partial<ScriptDTO>);
    }
}

/**
 * ScriptStatusDTO 进程状态传输对象
 */
export class ScriptStatusDTO {
    "id": number;

    /**
     * running, stopped, exited
     */
    "status": string;

    /**
     * 退出码（仅 exited 状态有值）
     */
    "exitCode": number;

    /**
     * 进程 PID（root，通常是 cmd）
     */
    "pid": number;

    /**
     * 实际子进程 PID（如 node/python），0 表示未知
     */
    "childPid": number;

    /**
     * 监听端口列表，如 ["3000", "8080"]
     */
    "ports": string[];

    /** Creates a new ScriptStatusDTO instance. */
    constructor($$source: Partial<ScriptStatusDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("childPid" in $$source)) {
            this["childPid"] = 0;
        }
        if (!("ports" in $$source)) {
            this["ports"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptStatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptStatusDTO {
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField5_0($$parsedSource["ports"]);
        }
        return new ScriptStatusDTO($$parsedSource as Partial<ScriptStatusDTO>);
    }
}

/**
 * TagDTO 标签传输对象
 */
export class TagDTO {
    "id": number;
    "name": string;
    "color": string;

    /** Creates a new TagDTO instance. */
    constructor($$source: Partial<TagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagDTO($$parsedSource as Partial<TagDTO>);
    }
}

// Private type creation functions
const $$createType0 = CategoryDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = TagDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
