// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CategoryDTO 分类传输对象（含树形 children）
 */
export class CategoryDTO {
    /**
     * Creates a new CategoryDTO instance.
     * @param {Partial<CategoryDTO>} [$$source = {}] - The source object to create the CategoryDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["parentId"] = null;
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["order"] = 0;
        }
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {(CategoryDTO | null)[]}
             */
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CategoryDTO}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new CategoryDTO(/** @type {Partial<CategoryDTO>} */($$parsedSource));
    }
}

/**
 * EntryDTO 前端交互的数据传输对象
 */
export class EntryDTO {
    /**
     * Creates a new EntryDTO instance.
     * @param {Partial<EntryDTO>} [$$source = {}] - The source object to create the EntryDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("categoryId" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["categoryId"] = null;
        }
        if (!("categoryName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["categoryName"] = "";
        }
        if (!("tagIds" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["tagIds"] = [];
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {TagDTO[]}
             */
            this["tags"] = [];
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntryDTO}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tagIds" in $$parsedSource) {
            $$parsedSource["tagIds"] = $$createField7_0($$parsedSource["tagIds"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new EntryDTO(/** @type {Partial<EntryDTO>} */($$parsedSource));
    }
}

/**
 * LogLineDTO 日志行传输对象
 */
export class LogLineDTO {
    /**
     * Creates a new LogLineDTO instance.
     * @param {Partial<LogLineDTO>} [$$source = {}] - The source object to create the LogLineDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("scriptId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scriptId"] = 0;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * stdout or stderr
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLineDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogLineDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLineDTO(/** @type {Partial<LogLineDTO>} */($$parsedSource));
    }
}

/**
 * ProjectDTO 前端传输对象
 */
export class ProjectDTO {
    /**
     * Creates a new ProjectDTO instance.
     * @param {Partial<ProjectDTO>} [$$source = {}] - The source object to create the ProjectDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["order"] = 0;
        }
        if (!("scriptCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scriptCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectDTO(/** @type {Partial<ProjectDTO>} */($$parsedSource));
    }
}

/**
 * ScriptDTO 前端传输对象
 */
export class ScriptDTO {
    /**
     * Creates a new ScriptDTO instance.
     * @param {Partial<ScriptDTO>} [$$source = {}] - The source object to create the ScriptDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("workDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workDir"] = "";
        }
        if (!("envVars" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["envVars"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("elevated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["elevated"] = false;
        }
        if (!("keepWindow" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepWindow"] = false;
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["projectId"] = null;
        }
        if (!("projectName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectName"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptDTO(/** @type {Partial<ScriptDTO>} */($$parsedSource));
    }
}

/**
 * ScriptStatusDTO 进程状态传输对象
 */
export class ScriptStatusDTO {
    /**
     * Creates a new ScriptStatusDTO instance.
     * @param {Partial<ScriptStatusDTO>} [$$source = {}] - The source object to create the ScriptStatusDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * running, stopped, exited
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("exitCode" in $$source)) {
            /**
             * 退出码（仅 exited 状态有值）
             * @member
             * @type {number}
             */
            this["exitCode"] = 0;
        }
        if (!("pid" in $$source)) {
            /**
             * 进程 PID
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptStatusDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptStatusDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptStatusDTO(/** @type {Partial<ScriptStatusDTO>} */($$parsedSource));
    }
}

/**
 * TagDTO 标签传输对象
 */
export class TagDTO {
    /**
     * Creates a new TagDTO instance.
     * @param {Partial<TagDTO>} [$$source = {}] - The source object to create the TagDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TagDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagDTO(/** @type {Partial<TagDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = CategoryDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = TagDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
