// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCategory(arg1:string,arg2:any):Promise<void>;

export function CreateEntry(arg1:models.EntryDTO):Promise<void>;

export function CreateTag(arg1:string,arg2:string):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteEntry(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DisableHello():Promise<void>;

export function GetCategoryTree():Promise<Array<models.CategoryDTO>>;

export function GetEntries(arg1:any,arg2:any):Promise<Array<models.EntryDTO>>;

export function GetHelloAvailability():Promise<string>;

export function GetHelloCredential():Promise<Array<number>>;

export function GetPassword(arg1:number):Promise<string>;

export function GetTags():Promise<Array<models.TagDTO>>;

export function IsHelloEnabled():Promise<boolean>;

export function IsInitialized():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function Lock():Promise<void>;

export function OpenWindowsHelloSettings():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetupHello():Promise<void>;

export function SetupMasterKey(arg1:string):Promise<void>;

export function StoreHelloCredential(arg1:Array<number>):Promise<void>;

export function Unlock(arg1:string):Promise<boolean>;

export function UnlockWithHello():Promise<boolean>;

export function UpdateCategory(arg1:number,arg2:string,arg3:any):Promise<void>;

export function UpdateEntry(arg1:models.EntryDTO):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<void>;
