// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPathProfile(arg1) {
  return window['go']['main']['App']['ApplyPathProfile'](arg1);
}

export function CleanInvalidUserPaths() {
  return window['go']['main']['App']['CleanInvalidUserPaths']();
}

export function CreateCategory(arg1, arg2) {
  return window['go']['main']['App']['CreateCategory'](arg1, arg2);
}

export function CreateEntry(arg1) {
  return window['go']['main']['App']['CreateEntry'](arg1);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteEnvVar(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvVar'](arg1, arg2);
}

export function DeletePathProfile(arg1) {
  return window['go']['main']['App']['DeletePathProfile'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DiffAppendPrompts() {
  return window['go']['main']['App']['DiffAppendPrompts']();
}

export function DiffPresets() {
  return window['go']['main']['App']['DiffPresets']();
}

export function DisableHello() {
  return window['go']['main']['App']['DisableHello']();
}

export function ExpandEnvValue(arg1) {
  return window['go']['main']['App']['ExpandEnvValue'](arg1);
}

export function FetchAvailableModels() {
  return window['go']['main']['App']['FetchAvailableModels']();
}

export function FetchAvailableVersions(arg1, arg2) {
  return window['go']['main']['App']['FetchAvailableVersions'](arg1, arg2);
}

export function FetchMCPSkills() {
  return window['go']['main']['App']['FetchMCPSkills']();
}

export function ForceRefreshModels() {
  return window['go']['main']['App']['ForceRefreshModels']();
}

export function GetAppendPromptPath(arg1) {
  return window['go']['main']['App']['GetAppendPromptPath'](arg1);
}

export function GetAppendPromptStoreDir() {
  return window['go']['main']['App']['GetAppendPromptStoreDir']();
}

export function GetAppendPromptStoreStats() {
  return window['go']['main']['App']['GetAppendPromptStoreStats']();
}

export function GetCategoryTree() {
  return window['go']['main']['App']['GetCategoryTree']();
}

export function GetEntries(arg1, arg2) {
  return window['go']['main']['App']['GetEntries'](arg1, arg2);
}

export function GetEnvVar(arg1, arg2) {
  return window['go']['main']['App']['GetEnvVar'](arg1, arg2);
}

export function GetHelloAvailability() {
  return window['go']['main']['App']['GetHelloAvailability']();
}

export function GetHelloCredential() {
  return window['go']['main']['App']['GetHelloCredential']();
}

export function GetMainConfigPath() {
  return window['go']['main']['App']['GetMainConfigPath']();
}

export function GetOpenCodeAgentColors() {
  return window['go']['main']['App']['GetOpenCodeAgentColors']();
}

export function GetOpenCodeAgentLabels() {
  return window['go']['main']['App']['GetOpenCodeAgentLabels']();
}

export function GetOpenCodeAgentNames() {
  return window['go']['main']['App']['GetOpenCodeAgentNames']();
}

export function GetOpenCodeConfig() {
  return window['go']['main']['App']['GetOpenCodeConfig']();
}

export function GetOpenCodeConfigPath() {
  return window['go']['main']['App']['GetOpenCodeConfigPath']();
}

export function GetOpenCodeMCPs() {
  return window['go']['main']['App']['GetOpenCodeMCPs']();
}

export function GetOpenCodeSkills() {
  return window['go']['main']['App']['GetOpenCodeSkills']();
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function GetPathEntries() {
  return window['go']['main']['App']['GetPathEntries']();
}

export function GetPathResult() {
  return window['go']['main']['App']['GetPathResult']();
}

export function GetRuntimeConfig() {
  return window['go']['main']['App']['GetRuntimeConfig']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function ImportAppendPromptsFromFiles() {
  return window['go']['main']['App']['ImportAppendPromptsFromFiles']();
}

export function ImportPresetsFromConfig() {
  return window['go']['main']['App']['ImportPresetsFromConfig']();
}

export function InstallSDK(arg1, arg2) {
  return window['go']['main']['App']['InstallSDK'](arg1, arg2);
}

export function IsHelloEnabled() {
  return window['go']['main']['App']['IsHelloEnabled']();
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListEnvVars() {
  return window['go']['main']['App']['ListEnvVars']();
}

export function ListPathProfiles() {
  return window['go']['main']['App']['ListPathProfiles']();
}

export function ListSDKs() {
  return window['go']['main']['App']['ListSDKs']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OpenOpenCodeConfigDir() {
  return window['go']['main']['App']['OpenOpenCodeConfigDir']();
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function OpenWindowsHelloSettings() {
  return window['go']['main']['App']['OpenWindowsHelloSettings']();
}

export function PreviewMergeProfile(arg1) {
  return window['go']['main']['App']['PreviewMergeProfile'](arg1);
}

export function ReadAllAppendPrompts() {
  return window['go']['main']['App']['ReadAllAppendPrompts']();
}

export function ReadAppendPrompt(arg1) {
  return window['go']['main']['App']['ReadAppendPrompt'](arg1);
}

export function ReadMainConfig() {
  return window['go']['main']['App']['ReadMainConfig']();
}

export function RenamePathProfile(arg1, arg2) {
  return window['go']['main']['App']['RenamePathProfile'](arg1, arg2);
}

export function RestoreAppendPrompts() {
  return window['go']['main']['App']['RestoreAppendPrompts']();
}

export function SaveMainConfig(arg1) {
  return window['go']['main']['App']['SaveMainConfig'](arg1);
}

export function SaveOpenCodeConfig(arg1) {
  return window['go']['main']['App']['SaveOpenCodeConfig'](arg1);
}

export function SavePathEntries(arg1) {
  return window['go']['main']['App']['SavePathEntries'](arg1);
}

export function SavePathProfile(arg1) {
  return window['go']['main']['App']['SavePathProfile'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetEnvVar(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnvVar'](arg1, arg2, arg3);
}

export function SetRuntimeConfig(arg1) {
  return window['go']['main']['App']['SetRuntimeConfig'](arg1);
}

export function SetupHello() {
  return window['go']['main']['App']['SetupHello']();
}

export function SetupMasterKey(arg1) {
  return window['go']['main']['App']['SetupMasterKey'](arg1);
}

export function StoreHelloCredential(arg1) {
  return window['go']['main']['App']['StoreHelloCredential'](arg1);
}

export function SwitchSDK(arg1, arg2) {
  return window['go']['main']['App']['SwitchSDK'](arg1, arg2);
}

export function SyncPresetsToConfig() {
  return window['go']['main']['App']['SyncPresetsToConfig']();
}

export function UninstallSDK(arg1, arg2) {
  return window['go']['main']['App']['UninstallSDK'](arg1, arg2);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UnlockWithHello() {
  return window['go']['main']['App']['UnlockWithHello']();
}

export function UpdateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2, arg3);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}

export function WriteAppendPrompt(arg1, arg2) {
  return window['go']['main']['App']['WriteAppendPrompt'](arg1, arg2);
}
