// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1, arg2) {
  return window['go']['main']['App']['CreateCategory'](arg1, arg2);
}

export function CreateEntry(arg1) {
  return window['go']['main']['App']['CreateEntry'](arg1);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DisableHello() {
  return window['go']['main']['App']['DisableHello']();
}

export function GetCategoryTree() {
  return window['go']['main']['App']['GetCategoryTree']();
}

export function GetEntries(arg1, arg2) {
  return window['go']['main']['App']['GetEntries'](arg1, arg2);
}

export function GetHelloAvailability() {
  return window['go']['main']['App']['GetHelloAvailability']();
}

export function GetHelloCredential() {
  return window['go']['main']['App']['GetHelloCredential']();
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function IsHelloEnabled() {
  return window['go']['main']['App']['IsHelloEnabled']();
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function OpenWindowsHelloSettings() {
  return window['go']['main']['App']['OpenWindowsHelloSettings']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetupHello() {
  return window['go']['main']['App']['SetupHello']();
}

export function SetupMasterKey(arg1) {
  return window['go']['main']['App']['SetupMasterKey'](arg1);
}

export function StoreHelloCredential(arg1) {
  return window['go']['main']['App']['StoreHelloCredential'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UnlockWithHello() {
  return window['go']['main']['App']['UnlockWithHello']();
}

export function UpdateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2, arg3);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}
