// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {opencode} from '../models';
import {main} from '../models';
import {pathenv} from '../models';
import {runtime} from '../models';
import {envvars} from '../models';

export function ApplyPathProfile(arg1:string):Promise<void>;

export function CleanInvalidUserPaths():Promise<Array<string>>;

export function ClearScriptLogs(arg1:number):Promise<void>;

export function CreateCategory(arg1:string,arg2:any):Promise<void>;

export function CreateEntry(arg1:models.EntryDTO):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<models.ProjectDTO>;

export function CreateScript(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:boolean,arg8:number):Promise<models.ScriptDTO>;

export function CreateTag(arg1:string,arg2:string):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteEntry(arg1:number):Promise<void>;

export function DeleteEnvVar(arg1:string,arg2:boolean):Promise<void>;

export function DeletePathProfile(arg1:string):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteScript(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DiffAppendPrompts():Promise<Array<opencode.AppendPromptDiff>>;

export function DiffPresets():Promise<opencode.PresetDiff>;

export function DisableHello():Promise<void>;

export function ExpandEnvValue(arg1:string):Promise<string>;

export function FetchAvailableModels():Promise<Array<string>>;

export function FetchAvailableVersions(arg1:string,arg2:boolean):Promise<Array<string>>;

export function FetchMCPSkills():Promise<main.MCPSkillResult>;

export function ForceRefreshModels():Promise<Array<string>>;

export function GetAppendPromptPath(arg1:string):Promise<string>;

export function GetAppendPromptStoreDir():Promise<string>;

export function GetAppendPromptStoreStats():Promise<number>;

export function GetCategoryTree():Promise<Array<models.CategoryDTO>>;

export function GetEntries(arg1:any,arg2:any):Promise<Array<models.EntryDTO>>;

export function GetEnvVar(arg1:string,arg2:boolean):Promise<string>;

export function GetHelloAvailability():Promise<string>;

export function GetHelloCredential():Promise<Array<number>>;

export function GetMainConfigPath():Promise<string>;

export function GetOpenCodeAgentColors():Promise<Record<string, string>>;

export function GetOpenCodeAgentLabels():Promise<Record<string, string>>;

export function GetOpenCodeAgentNames():Promise<Array<string>>;

export function GetOpenCodeConfig():Promise<opencode.PresetStoreData>;

export function GetOpenCodeConfigPath():Promise<string>;

export function GetOpenCodeMCPs():Promise<Array<opencode.MCPInfo>>;

export function GetOpenCodeSkills():Promise<Array<opencode.SkillInfo>>;

export function GetPassword(arg1:number):Promise<string>;

export function GetPathEntries():Promise<Array<pathenv.PathEntry>>;

export function GetPathResult():Promise<pathenv.PathResult>;

export function GetRuntimeConfig():Promise<runtime.Config>;

export function GetScriptLogs(arg1:number):Promise<Array<models.LogLineDTO>>;

export function GetScriptStatus(arg1:number):Promise<models.ScriptStatusDTO>;

export function GetTags():Promise<Array<models.TagDTO>>;

export function ImportAppendPromptsFromFiles():Promise<number>;

export function ImportPresetsFromConfig():Promise<void>;

export function InstallSDK(arg1:string,arg2:string):Promise<void>;

export function IsHelloEnabled():Promise<boolean>;

export function IsInitialized():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function ListEnvVars():Promise<envvars.EnvResult>;

export function ListPathProfiles():Promise<Array<pathenv.PathProfileDTO>>;

export function ListProjects():Promise<Array<models.ProjectDTO>>;

export function ListSDKs():Promise<Array<runtime.SDKInfo>>;

export function ListScripts():Promise<Array<models.ScriptDTO>>;

export function Lock():Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenOpenCodeConfigDir():Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function OpenWindowsHelloSettings():Promise<void>;

export function PreviewMergeProfile(arg1:string):Promise<Array<string>>;

export function ReadAllAppendPrompts():Promise<Record<string, string>>;

export function ReadAppendPrompt(arg1:string):Promise<string>;

export function ReadMainConfig():Promise<opencode.MainConfig>;

export function RenamePathProfile(arg1:string,arg2:string):Promise<void>;

export function RestartScript(arg1:number):Promise<void>;

export function RestoreAppendPrompts():Promise<number>;

export function SaveMainConfig(arg1:opencode.MainConfig):Promise<void>;

export function SaveOpenCodeConfig(arg1:opencode.PresetStoreData):Promise<void>;

export function SavePathEntries(arg1:Array<string>):Promise<void>;

export function SavePathProfile(arg1:pathenv.PathProfileDTO):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetEnvVar(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetRuntimeConfig(arg1:string):Promise<void>;

export function SetupHello():Promise<void>;

export function SetupMasterKey(arg1:string):Promise<void>;

export function StartScript(arg1:number):Promise<void>;

export function StopScript(arg1:number):Promise<void>;

export function StoreHelloCredential(arg1:Array<number>):Promise<void>;

export function SwitchSDK(arg1:string,arg2:string):Promise<void>;

export function SyncPresetsToConfig():Promise<void>;

export function UninstallSDK(arg1:string,arg2:string):Promise<void>;

export function Unlock(arg1:string):Promise<boolean>;

export function UnlockWithHello():Promise<boolean>;

export function UpdateCategory(arg1:number,arg2:string,arg3:any):Promise<void>;

export function UpdateEntry(arg1:models.EntryDTO):Promise<void>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateScript(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean,arg9:number):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<void>;

export function WriteAppendPrompt(arg1:string,arg2:string):Promise<void>;
